# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 03:58
from __future__ import unicode_literals

from django.db import migrations
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20160524_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=forum.models.ListField(default=[]),
        ),
        migrations.AddField(
            model_name='thread',
            name='comments',
            field=forum.models.ListField(default=[]),
        ),
    ]
