# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20160524_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='comments',
        ),
    ]
